name: Run_Adblock_Reject_JSON31 # 工作流名称

on:
  schedule:
    - cron: '*/240 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本作为运行环境

    steps:
    - name: Setup Node.js 20  # 设置 Node.js 20 环境
      uses: actions/setup-node@v3  # 使用官方的 setup-node 操作来设置 Node.js 环境
      with:
        node-version: '20'  # 指定使用 Node.js 版本 20

    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v3  # 使用官方的 checkout 操作来检出代码

    # -------------------------- 新增：Git LFS 集成步骤 --------------------------
    - name: Install Git LFS  # 安装 Git LFS（Ubuntu 镜像默认未安装）
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git-lfs

    - name: Initialize Git LFS  # 初始化 Git LFS 客户端
      run: git lfs install

    - name: Track Large Files with Git LFS  # 配置 LFS 跟踪规则（根据需求调整文件匹配符）
      run: |
        # 跟踪所有 .srs 文件（若只需跟踪特定文件，可替换为 "adblock_reject31.srs"）
        git lfs track "*.srs"
        # 将 LFS 跟踪配置（.gitattributes）添加到暂存区
        git add .gitattributes
    # ---------------------------------------------------------------------------

    - name: Install PowerShell 7  # 安装 PowerShell 7
      run: |
        sudo apt-get update  # 更新包列表
        sudo apt-get install -y wget apt-transport-https software-properties-common  # 安装必要的包
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb  # 下载微软的包配置文件
        sudo dpkg -i packages-microsoft-prod.deb  # 安装包配置文件
        wget https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box-1.11.15-linux-amd64.tar.gz
        tar -zxvf sing-box-1.11.15-linux-amd64.tar.gz
        sudo apt-get update  # 更新包列表
        sudo apt-get install -y powershell  # 安装 PowerShell 7
        sudo apt install bash
        rm packages-microsoft-prod.deb  # 删除包配置文件

    - name: Run adblock_rule_generator_json31.ps1   # 运行 adblock_rule_generator_json.ps1 脚本
      run: pwsh -File ./adblock_rule_generator_json31.ps1  # 使用 PowerShell 7 运行脚本

    - name: convert  # 转换规则集为 .srs 格式（依赖 sing-box）
      shell: bash
      run: sing-box-1.11.15-linux-amd64/sing-box rule-set compile --output adblock_reject31.srs adblock_reject31.json
      
    - name: Force Add and Commit JSON file  # 强制添加并提交 .srs 文件
      run: |
        git config --global user.name 'github-actions'  # 配置提交用户名
        git config --global user.email 'github-actions@github.com'  # 配置提交邮箱
        # 若 LFS 跟踪生效，通常无需 -f；保留以防文件已被缓存
        git add -f adblock_reject31.srs  
        git commit -m 'Update adblock_reject31.srs' || git commit --allow-empty -m 'Empty commit to force push'

    - name: Retry Push JSON file  # 推送更改（含 LFS 对象）
      env:
        TOKEN: ${{ secrets.TOKEN }}  # 使用 GitHub 密钥进行身份验证
      run: |
        for i in {1..5}; do  # 最多重试5次
          git push --force origin HEAD && exit 0 || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
        done